# Generated by Django 5.1.4 on 2024-12-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0009_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
