# Generated by Django 5.1.4 on 2024-12-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0010_remove_appointment_doctor_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='Unknown Doctor', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
