# Generated by Django 5.1.4 on 2024-12-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0012_patient_user_alter_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
